---

name: build

# on: 
#   schedule:
#     - cron: '30 2 15 * *'

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  vyos_version: 1.4

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: write

  #   container:
  #     image: vyos/vyos-build:current
  #     volumes:
  #       - /proc:/proc
  #     options: --privileged

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Generate Version
  #       run: |
  #         echo "version=${{ env.version }}-dev-$(git rev-parse --short HEAD)" >>$GITHUB_ENV
      
  #     - name: Executing scripts
  #       run: find scripts -name '*.sh' -exec bash {} \;

  #     - name: Clone Repository
  #       run: git clone -b ${{ env.branch }} --single-branch --depth 1 https://github.com/vyos/vyos-build.git

  #     - name: Configure
  #       working-directory: vyos-build
  #       run: ./configure --architecture amd64 --build-by "https://github.com/os-builds" --build-type release --version ${{ env.version }}

  #     - name: Prepare custom packages
  #       run: |
  #         for deb in $(cat packages.txt); do
  #           mv ${deb} vyos-build/packages/
  #         done

  #     - name: Build ISO
  #       working-directory: vyos-build
  #       run: sudo make iso

  #     - name: Rename ISO
  #       run: mv vyos-build/build/live-image-amd64.hybrid.iso vyos-${{ env.version }}.iso

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: vyos-${{ env.version }}
  #         path: vyos-${{ env.version }}.iso

  #     - name: Checksums
  #       id: checksums
  #       run: |
  #         echo "md5sum=$(md5sum vyos-${{ env.version }}.iso | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
  #         echo "sha256sum=$(sha256sum vyos-${{ env.version }}.iso | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
  #         echo "sha512sum=$(sha512sum vyos-${{ env.version }}.iso | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

  convert:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Clone Repository
        run: git clone -b ${{ env.branch }} --single-branch --depth 1 https://github.com/vyos/vyos-vm-images.git

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Build qcow2 image
        working-directory: vyos-vm-images
        run: ansible-playbook qemu.yml -e cloud_init=true -e cloud_init_disable_config=true -e cloud_init_ds=NoCloud -e grub_console=serial  -e guest_agent=qemu -e keep_user=true -e enable_ssh=true -e enable_dhcp=true -e disk_size=20 -e parttable_type=mbr

